### ISSUE TITLE
Error retrieving a new session from the selenium server

### ISSUE THREAD

**Issue by RhodesPeter** [RhodesPeter/portfolio#6]
Came back to the project and ran nightwatch.js tests, no code has been changed from when the tests were last run and I have this error in my terminal:

```
peterrhodes (master *) cv-portfolio $ npm test

> cv-portfolio@1.0.0 test /Users/peterrhodes/Desktop/cv-portfolio
> nightwatch --config tests/nightwatch.conf.BASIC.js

Starting selenium server... started - PID:  52034

[Tests] Test Suite
======================

Running:  Assert Title

Error retrieving a new session from the selenium server

Connection refused! Is selenium server started?
{ Error: getaddrinfo ENOTFOUND localhost localhost:4444
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost',
  host: 'localhost',
  port: 4444 }
```

**Comment by RhodesPeter** [comment]
Update - I returned home and the tests are working. I was using Starbucks internet, does the network I am using have an effect on selenium?

**Comment by RhodesPeter** [comment]
Wow! Of all my choices for a cafe: 

https://www.reddit.com/r/selenium/comments/4b5sej/selenium_webdriver_blocked_on_starbuckscom_any/

http://stackoverflow.com/questions/36109320/selenium-webdriver-blocked-on-starbucks-com-any-way-around

**Comment by RhodesPeter** [comment]
This issue was no longer present when I changed from the nightwatch.conf.BASIC.js to nightwatch.conf.js
